//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portal.Properties.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USU_AutorizaLogin.
        /// </summary>
        internal static string PROCEDURE_AUTORIZA_LOGIN {
            get {
                return ResourceManager.GetString("PROCEDURE_AUTORIZA_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USU_BuscarUsuarioPeloLogin.
        /// </summary>
        internal static string PROCEDURE_BUSCAR_USUARIO {
            get {
                return ResourceManager.GetString("PROCEDURE_BUSCAR_USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FNR_RelatorioFuncionarios.
        /// </summary>
        internal static string PROCEDURE_RELAT_FUNCIONARIOS {
            get {
                return ResourceManager.GetString("PROCEDURE_RELAT_FUNCIONARIOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///  FROM FolhaDePontoWeb_DDaniel.dbo.TAB_USUARIO
        ///  WHERE LOGIN_USUARIO = @login
        ///  and
        ///  SENHA_USUARIO = @senha.
        /// </summary>
        internal static string QUERY_OBTER_USUARIO_PARA_LOGIN {
            get {
                return ResourceManager.GetString("QUERY_OBTER_USUARIO_PARA_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///  FROM FolhaDePontoWeb_DDaniel.dbo.TAB_USUARIO
        ///  WHERE LOGIN_USUARIO = @login.
        /// </summary>
        internal static string QUERY_OBTER_USUARIO_PELO_LOGIN {
            get {
                return ResourceManager.GetString("QUERY_OBTER_USUARIO_PELO_LOGIN", resourceCulture);
            }
        }
    }
}
